### ISSUE TITLE
能在virtualBox里运行么？

### ISSUE THREAD

**Issue by robertding** [bajdcc/MiniOS#1]
RT

**Comment by bajdcc** [comment]
没试过，但在bochs和qemu都能运行，因为镜像文件是img格式的，你看看vbox能不能加载img

**Comment by bajdcc** [comment]
下个了vb运行了一下：

![mos](https://cloud.githubusercontent.com/assets/4200516/24188343/f50df1b6-0f1b-11e7-959e-6f084bbf93c3.png)

把ubuntu中minios/bin/floppy.img作为软盘启动即可。
